/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardCardsSearchRouteImport } from './routes/dashboard/cards/search'
import { Route as DashboardCardsNewRouteImport } from './routes/dashboard/cards/new'
import { Route as DashboardCardsIdRouteImport } from './routes/dashboard/cards/$id'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin/settings'
import { Route as DashboardAdminInvitationsRouteImport } from './routes/dashboard/admin/invitations'
import { Route as DashboardAdminCostTrackingRouteImport } from './routes/dashboard/admin/cost-tracking'
import { Route as DashboardAdminContentModerationRouteImport } from './routes/dashboard/admin/content-moderation'
import { Route as DashboardAdminUsersUserIdRouteImport } from './routes/dashboard/admin/users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/dashboard/settings/',
  path: '/dashboard/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/dashboard/admin/',
  path: '/dashboard/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCardsSearchRoute = DashboardCardsSearchRouteImport.update({
  id: '/dashboard/cards/search',
  path: '/dashboard/cards/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCardsNewRoute = DashboardCardsNewRouteImport.update({
  id: '/dashboard/cards/new',
  path: '/dashboard/cards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCardsIdRoute = DashboardCardsIdRouteImport.update({
  id: '/dashboard/cards/$id',
  path: '/dashboard/cards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/dashboard/admin/settings',
  path: '/dashboard/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminInvitationsRoute =
  DashboardAdminInvitationsRouteImport.update({
    id: '/dashboard/admin/invitations',
    path: '/dashboard/admin/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminCostTrackingRoute =
  DashboardAdminCostTrackingRouteImport.update({
    id: '/dashboard/admin/cost-tracking',
    path: '/dashboard/admin/cost-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminContentModerationRoute =
  DashboardAdminContentModerationRouteImport.update({
    id: '/dashboard/admin/content-moderation',
    path: '/dashboard/admin/content-moderation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminUsersUserIdRoute =
  DashboardAdminUsersUserIdRouteImport.update({
    id: '/dashboard/admin/users/$userId',
    path: '/dashboard/admin/users/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/content-moderation': typeof DashboardAdminContentModerationRoute
  '/dashboard/admin/cost-tracking': typeof DashboardAdminCostTrackingRoute
  '/dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/cards/$id': typeof DashboardCardsIdRoute
  '/dashboard/cards/new': typeof DashboardCardsNewRoute
  '/dashboard/cards/search': typeof DashboardCardsSearchRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/dashboard/admin/content-moderation': typeof DashboardAdminContentModerationRoute
  '/dashboard/admin/cost-tracking': typeof DashboardAdminCostTrackingRoute
  '/dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/cards/$id': typeof DashboardCardsIdRoute
  '/dashboard/cards/new': typeof DashboardCardsNewRoute
  '/dashboard/cards/search': typeof DashboardCardsSearchRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/content-moderation': typeof DashboardAdminContentModerationRoute
  '/dashboard/admin/cost-tracking': typeof DashboardAdminCostTrackingRoute
  '/dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/cards/$id': typeof DashboardCardsIdRoute
  '/dashboard/cards/new': typeof DashboardCardsNewRoute
  '/dashboard/cards/search': typeof DashboardCardsSearchRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/profile/$username'
    | '/dashboard/'
    | '/dashboard/admin/content-moderation'
    | '/dashboard/admin/cost-tracking'
    | '/dashboard/admin/invitations'
    | '/dashboard/admin/settings'
    | '/dashboard/cards/$id'
    | '/dashboard/cards/new'
    | '/dashboard/cards/search'
    | '/dashboard/admin/'
    | '/dashboard/settings/'
    | '/dashboard/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/profile/$username'
    | '/dashboard/admin/content-moderation'
    | '/dashboard/admin/cost-tracking'
    | '/dashboard/admin/invitations'
    | '/dashboard/admin/settings'
    | '/dashboard/cards/$id'
    | '/dashboard/cards/new'
    | '/dashboard/cards/search'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/dashboard/_layout'
    | '/profile/$username'
    | '/dashboard/'
    | '/dashboard/admin/content-moderation'
    | '/dashboard/admin/cost-tracking'
    | '/dashboard/admin/invitations'
    | '/dashboard/admin/settings'
    | '/dashboard/cards/$id'
    | '/dashboard/cards/new'
    | '/dashboard/cards/search'
    | '/dashboard/admin/'
    | '/dashboard/settings/'
    | '/dashboard/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminContentModerationRoute: typeof DashboardAdminContentModerationRoute
  DashboardAdminCostTrackingRoute: typeof DashboardAdminCostTrackingRoute
  DashboardAdminInvitationsRoute: typeof DashboardAdminInvitationsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardCardsIdRoute: typeof DashboardCardsIdRoute
  DashboardCardsNewRoute: typeof DashboardCardsNewRoute
  DashboardCardsSearchRoute: typeof DashboardCardsSearchRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardAdminUsersUserIdRoute: typeof DashboardAdminUsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cards/search': {
      id: '/dashboard/cards/search'
      path: '/dashboard/cards/search'
      fullPath: '/dashboard/cards/search'
      preLoaderRoute: typeof DashboardCardsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cards/new': {
      id: '/dashboard/cards/new'
      path: '/dashboard/cards/new'
      fullPath: '/dashboard/cards/new'
      preLoaderRoute: typeof DashboardCardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cards/$id': {
      id: '/dashboard/cards/$id'
      path: '/dashboard/cards/$id'
      fullPath: '/dashboard/cards/$id'
      preLoaderRoute: typeof DashboardCardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/dashboard/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/invitations': {
      id: '/dashboard/admin/invitations'
      path: '/dashboard/admin/invitations'
      fullPath: '/dashboard/admin/invitations'
      preLoaderRoute: typeof DashboardAdminInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/cost-tracking': {
      id: '/dashboard/admin/cost-tracking'
      path: '/dashboard/admin/cost-tracking'
      fullPath: '/dashboard/admin/cost-tracking'
      preLoaderRoute: typeof DashboardAdminCostTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/content-moderation': {
      id: '/dashboard/admin/content-moderation'
      path: '/dashboard/admin/content-moderation'
      fullPath: '/dashboard/admin/content-moderation'
      preLoaderRoute: typeof DashboardAdminContentModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users/$userId': {
      id: '/dashboard/admin/users/$userId'
      path: '/dashboard/admin/users/$userId'
      fullPath: '/dashboard/admin/users/$userId'
      preLoaderRoute: typeof DashboardAdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminContentModerationRoute: DashboardAdminContentModerationRoute,
  DashboardAdminCostTrackingRoute: DashboardAdminCostTrackingRoute,
  DashboardAdminInvitationsRoute: DashboardAdminInvitationsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardCardsIdRoute: DashboardCardsIdRoute,
  DashboardCardsNewRoute: DashboardCardsNewRoute,
  DashboardCardsSearchRoute: DashboardCardsSearchRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardAdminUsersUserIdRoute: DashboardAdminUsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
